# Get all tasks
GET http://localhost:3001/tasks HTTP/1.1
Content-Type: application/json

###

# Create a Task
POST http://localhost:3001/tasks HTTP/1.1
Content-Type: application/json

###

# Update a Task
PUT http://localhost:3001/tasks HTTP/1.1
Content-Type: application/json

###

# Delete a Task
DELETE http://localhost:3001/tasks HTTP/1.1
Content-Type: application/json